[package]
version = "1.0.1" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Example C++ Extension: OmniGraph Node"
description = "Demonstrates how to create a C++ node for OmniGraph"
category = "Example"
keywords = ["example", "C++", "cpp", "Graph", "Node", "OmniGraph"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["Kevin Picott <kpicott@nvidia.com>", "David Bosnich <dbosnich@nvidia.com>"]
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template-cpp"

[dependencies]
"omni.graph.core" = {}
"omni.graph.tools" = {}

[[python.module]]
name = "omni.example.cpp.omnigraph_node"

[[native.plugin]]
path = "bin/*.plugin"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
